import { CustomAgentNode, CustomAgentEdge } from "./types";

export function generatePythonCode(
  graphName: string,
  nodes: CustomAgentNode[],
  edges: CustomAgentEdge[]
): string {
  const sanitizeId = (id: string) => id.replace(/[^a-zA-Z0-9_]/g, "_");

  // Determine entry point (node with no incoming edges)
  const targetIds = new Set(edges.map((e) => e.target));
  const entryNode = nodes.find((n) => !targetIds.has(n.id)) || nodes[0];
  const entryId = entryNode ? sanitizeId(entryNode.id) : "start";

  let py = `"""
${graphName} — Generated by Dynavec Agent Studio
Powered by dynavec.agents orchestration engine.
"""

from typing import Any, Dict
from dynavec.agents import (
    AgentGraph,
    BaseNode,
    RetrieverNode,
    LLMNode,
    GuardNode,
    ResponseNode,
)

# 1. Initialize Agent Graph
graph = AgentGraph(name="${graphName || "Agent Workflow"}")

# 2. Register Nodes
`;

  nodes.forEach((n) => {
    const varName = sanitizeId(n.id);
    const cfg = n.data.config || {};

    if (n.data.type === "retriever") {
      py += `# ${n.data.label}\n`;
      py += `graph.add_node(\n`;
      py += `    "${varName}",\n`;
      py += `    RetrieverNode(\n`;
      py += `        namespace="${cfg.namespace || "default"}",\n`;
      py += `        top_k=${cfg.top_k || 5},\n`;
      py += `        metric="${cfg.metric || "cosine"}",\n`;
      if (cfg.filter_expr) {
        py += `        filter_expr="${cfg.filter_expr}",\n`;
      }
      py += `    )\n`;
      py += `)\n\n`;
    } else if (n.data.type === "llm") {
      py += `# ${n.data.label}\n`;
      py += `graph.add_node(\n`;
      py += `    "${varName}",\n`;
      py += `    LLMNode(\n`;
      py += `        model="${cfg.model || "gpt-4o"}",\n`;
      py += `        temperature=${cfg.temperature ?? 0.2},\n`;
      py += `        max_tokens=${cfg.max_tokens || 1024},\n`;
      if (cfg.system_prompt) {
        py += `        system_prompt="""${cfg.system_prompt}""",\n`;
      }
      py += `    )\n`;
      py += `)\n\n`;
    } else if (n.data.type === "guard") {
      py += `# ${n.data.label} (Threshold Gate)\n`;
      py += `graph.add_node(\n`;
      py += `    "${varName}",\n`;
      py += `    GuardNode(\n`;
      py += `        threshold=${cfg.threshold ?? 0.85},\n`;
      py += `        metric_name="${cfg.metric_name || "relevance"}",\n`;
      py += `    )\n`;
      py += `)\n\n`;
    } else if (n.data.type === "response") {
      py += `# ${n.data.label}\n`;
      py += `graph.add_node(\n`;
      py += `    "${varName}",\n`;
      py += `    ResponseNode(\n`;
      py += `        template="Answer: {response}",\n`;
      py += `    )\n`;
      py += `)\n\n`;
    } else {
      py += `# Custom Node: ${n.data.label} (${n.data.type})\n`;
      py += `class Custom_${varName}(BaseNode):\n`;
      py += `    def execute(self, state: Dict[str, Any]) -> Dict[str, Any]:\n`;
      py += `        # Node configuration: ${JSON.stringify(cfg)}\n`;
      py += `        return state\n\n`;
      py += `graph.add_node("${varName}", Custom_${varName}())\n\n`;
    }
  });

  py += `# 3. Wire Graph Edges\n`;

  // Group edges by source
  const edgesBySource: Record<string, CustomAgentEdge[]> = {};
  edges.forEach((e) => {
    if (!edgesBySource[e.source]) edgesBySource[e.source] = [];
    edgesBySource[e.source].push(e);
  });

  Object.entries(edgesBySource).forEach(([src, edgeList]) => {
    const srcNode = nodes.find((n) => n.id === src);
    const srcVar = sanitizeId(src);

    if (srcNode?.data.type === "guard" && edgeList.length > 1) {
      // Conditional branching
      const passEdge = edgeList.find((e) => e.sourceHandle === "pass");
      const failEdge = edgeList.find((e) => e.sourceHandle === "fail");
      const passTarget = passEdge ? sanitizeId(passEdge.target) : srcVar;
      const failTarget = failEdge ? sanitizeId(failEdge.target) : srcVar;

      py += `graph.add_conditional_edge(\n`;
      py += `    "${srcVar}",\n`;
      py += `    path=lambda state: "pass" if state.get("passed", True) else "fail",\n`;
      py += `    path_map={"pass": "${passTarget}", "fail": "${failTarget}"}\n`;
      py += `)\n`;
    } else if (srcNode?.data.type === "cache" && edgeList.length > 1) {
      const hitEdge = edgeList.find((e) => e.sourceHandle === "hit");
      const missEdge = edgeList.find((e) => e.sourceHandle === "miss");
      const hitTarget = hitEdge ? sanitizeId(hitEdge.target) : srcVar;
      const missTarget = missEdge ? sanitizeId(missEdge.target) : srcVar;

      py += `graph.add_conditional_edge(\n`;
      py += `    "${srcVar}",\n`;
      py += `    path=lambda state: "hit" if state.get("cache_hit", False) else "miss",\n`;
      py += `    path_map={"hit": "${hitTarget}", "miss": "${missTarget}"}\n`;
      py += `)\n`;
    } else {
      edgeList.forEach((e) => {
        py += `graph.add_edge("${srcVar}", "${sanitizeId(e.target)}")\n`;
      });
    }
  });

  py += `\n# 4. Set Entry Point\n`;
  py += `graph.set_entry_point("${entryId}")\n\n`;

  py += `# 5. Compile & Run Simulation\n`;
  py += `if __name__ == "__main__":\n`;
  py += `    test_query = "How does dynavec achieve sub-10ms vector search?"\n`;
  py += `    print(f"Executing agent with query: {test_query}")\n`;
  py += `    result = graph.run(initial_state={"query": test_query})\n`;
  py += `    print("Final State Output:")\n`;
  py += `    print(result.state)\n`;
  py += `    print(f"Total Execution Time: {result.total_latency_ms:.2f}ms")\n`;
  py += `    print(f"Traced Steps: {len(result.traces)}")\n`;

  return py;
}
