import { CustomAgentNode, CustomAgentEdge, WorkflowTemplate } from "./types";

export const DEFAULT_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "enterprise-rag-guardrails",
    name: "Enterprise RAG with Guardrails",
    description: "Production-grade retrieval augmented generation with semantic caching, Dynavec vector search, confidence threshold guard, and LLM synthesis.",
    category: "RAG",
    tags: ["Production", "Dynavec Native", "Guardrails", "Caching"],
    nodes: [
      {
        id: "node-cache",
        type: "agentNode",
        position: { x: 50, y: 180 },
        data: {
          label: "Semantic Cache",
          type: "cache",
          description: "Check DynamoDB semantic vector cache (<5ms)",
          config: {
            similarity_threshold: 0.94,
            ttl_seconds: 86400,
            cache_namespace: "enterprise-prod",
          },
        },
      },
      {
        id: "node-retriever",
        type: "agentNode",
        position: { x: 380, y: 260 },
        data: {
          label: "Dynavec Retriever",
          type: "retriever",
          description: "S3 Vectors + DynamoDB hybrid namespace retrieval",
          config: {
            namespace: "knowledge-base",
            top_k: 5,
            metric: "cosine",
            filter_expr: "department = 'engineering'",
            hybrid_alpha: 0.75,
          },
        },
      },
      {
        id: "node-reranker",
        type: "agentNode",
        position: { x: 710, y: 260 },
        data: {
          label: "Cross-Encoder Reranker",
          type: "reranker",
          description: "Rerank top chunks using MMR and cross-encoder",
          config: {
            strategy: "cross-encoder/ms-marco-MiniLM-L-6-v2",
            top_n: 3,
            diversity_penalty: 0.3,
          },
        },
      },
      {
        id: "node-guard",
        type: "agentNode",
        position: { x: 1040, y: 260 },
        data: {
          label: "Confidence & Safety Guard",
          type: "guard",
          description: "Block hallucinations or low-confidence context",
          config: {
            threshold: 0.82,
            metric_name: "context_relevance",
            fallback_message: "I could not find sufficiently reliable context to answer this query safely.",
          },
        },
      },
      {
        id: "node-llm",
        type: "agentNode",
        position: { x: 1380, y: 200 },
        data: {
          label: "LLM Synthesizer",
          type: "llm",
          description: "Synthesize response with citations from context",
          config: {
            model: "gpt-4o",
            temperature: 0.2,
            max_tokens: 1024,
            system_prompt: "You are an enterprise AI assistant powered by dynavec. Answer only using the verified retrieved context and cite source chunks.",
          },
        },
      },
      {
        id: "node-response",
        type: "agentNode",
        position: { x: 1720, y: 180 },
        data: {
          label: "Response Delivery",
          type: "response",
          description: "Format output with telemetry, tokens and latency headers",
          config: {
            include_citations: true,
            format: "markdown",
            streaming: true,
          },
        },
      },
    ],
    edges: [
      {
        id: "e-cache-hit",
        source: "node-cache",
        sourceHandle: "hit",
        target: "node-response",
        animated: true,
        label: "Cache Hit (instant)",
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
      {
        id: "e-cache-miss",
        source: "node-cache",
        sourceHandle: "miss",
        target: "node-retriever",
        label: "Cache Miss",
        style: { stroke: "#64748b", strokeWidth: 2 },
      },
      {
        id: "e-retriever-rerank",
        source: "node-retriever",
        target: "node-reranker",
        style: { stroke: "#64748b", strokeWidth: 2 },
      },
      {
        id: "e-rerank-guard",
        source: "node-reranker",
        target: "node-guard",
        style: { stroke: "#64748b", strokeWidth: 2 },
      },
      {
        id: "e-guard-pass",
        source: "node-guard",
        sourceHandle: "pass",
        target: "node-llm",
        label: "Passed (>0.82)",
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
      {
        id: "e-guard-fail",
        source: "node-guard",
        sourceHandle: "fail",
        target: "node-response",
        label: "Blocked / Fallback",
        style: { stroke: "#ef4444", strokeWidth: 2, strokeDasharray: "4 4" },
      },
      {
        id: "e-llm-response",
        source: "node-llm",
        target: "node-response",
        animated: true,
        style: { stroke: "#e8623b", strokeWidth: 2 },
      },
    ],
  },
  {
    id: "self-reflective-rag",
    name: "Self-Reflective RAG (Inline Eval Loop)",
    description: "Evaluates LLM generation against retrieved context with RAGAS faithfulness metrics. Automatically retries if hallucination is detected.",
    category: "Observability",
    tags: ["RAGAS", "Reflection", "Self-Correction"],
    nodes: [
      {
        id: "node-sr-retriever",
        type: "agentNode",
        position: { x: 50, y: 150 },
        data: {
          label: "Dynavec Knowledge Search",
          type: "retriever",
          description: "Search vector store with namespace filtering",
          config: { namespace: "kb-support", top_k: 4, metric: "cosine" },
        },
      },
      {
        id: "node-sr-llm",
        type: "agentNode",
        position: { x: 420, y: 150 },
        data: {
          label: "Draft Synthesizer",
          type: "llm",
          description: "Draft initial response from context",
          config: { model: "claude-3-5-sonnet", temperature: 0.3, max_tokens: 800 },
        },
      },
      {
        id: "node-sr-eval",
        type: "agentNode",
        position: { x: 790, y: 150 },
        data: {
          label: "RAGAS Faithfulness Evaluator",
          type: "eval",
          description: "Calculates faithfulness & context precision score",
          config: {
            metrics: ["faithfulness", "answer_relevance"],
            min_score: 0.85,
            auto_retry: true,
            max_retries: 2,
          },
        },
      },
      {
        id: "node-sr-response",
        type: "agentNode",
        position: { x: 1180, y: 150 },
        data: {
          label: "Verified Answer",
          type: "response",
          description: "Delivers verified, evaluated response with audit certificate",
          config: { format: "json", attach_eval_metrics: true },
        },
      },
    ],
    edges: [
      { id: "e-sr-1", source: "node-sr-retriever", target: "node-sr-llm" },
      { id: "e-sr-2", source: "node-sr-llm", target: "node-sr-eval" },
      {
        id: "e-sr-retry",
        source: "node-sr-eval",
        sourceHandle: "fail",
        target: "node-sr-retriever",
        label: "Retry / Rewrite (Eval < 0.85)",
        style: { stroke: "#ef4444", strokeDasharray: "4 4" },
      },
      {
        id: "e-sr-pass",
        source: "node-sr-eval",
        sourceHandle: "pass",
        target: "node-sr-response",
        label: "Certified Pass",
        style: { stroke: "#10b981", strokeWidth: 2 },
      },
    ],
  },
  {
    id: "multi-agent-router",
    name: "Intent Classifier & Multi-Agent Router",
    description: "Semantically classifies inbound query and branches execution into technical docs, transactional billing API, or general support flow.",
    category: "Autonomous",
    tags: ["Intent Routing", "API Calling", "Multi-Agent"],
    nodes: [
      {
        id: "node-mar-classifier",
        type: "agentNode",
        position: { x: 60, y: 220 },
        data: {
          label: "Query Intent Classifier",
          type: "classifier",
          description: "Routes user input to domain specialist branch",
          config: {
            categories: ["doc_search", "api_action", "general_qa"],
            confidence_threshold: 0.8,
          },
        },
      },
      {
        id: "node-mar-retriever",
        type: "agentNode",
        position: { x: 480, y: 60 },
        data: {
          label: "Dynavec Docs Vector Store",
          type: "retriever",
          description: "Retrieve technical documentation",
          config: { namespace: "tech-docs", top_k: 5 },
        },
      },
      {
        id: "node-mar-http",
        type: "agentNode",
        position: { x: 480, y: 220 },
        data: {
          label: "Billing / Account API",
          type: "http",
          description: "Fetch live customer balance from REST endpoint",
          config: {
            url: "https://api.internal/v1/customer/status",
            method: "POST",
            auth_header: "Bearer env(API_KEY)",
          },
        },
      },
      {
        id: "node-mar-general",
        type: "agentNode",
        position: { x: 480, y: 380 },
        data: {
          label: "Fast General Chat",
          type: "llm",
          description: "Lightweight conversational response",
          config: { model: "gpt-4o-mini", temperature: 0.7 },
        },
      },
      {
        id: "node-mar-response",
        type: "agentNode",
        position: { x: 920, y: 220 },
        data: {
          label: "Agent Output",
          type: "response",
          description: "Merged branch response",
          config: { format: "markdown" },
        },
      },
    ],
    edges: [
      {
        id: "e-route-docs",
        source: "node-mar-classifier",
        sourceHandle: "route-0",
        target: "node-mar-retriever",
        label: "tech_docs",
        style: { stroke: "#3b82f6" },
      },
      {
        id: "e-route-api",
        source: "node-mar-classifier",
        sourceHandle: "route-1",
        target: "node-mar-http",
        label: "billing_api",
        style: { stroke: "#8b5cf6" },
      },
      {
        id: "e-route-general",
        source: "node-mar-classifier",
        sourceHandle: "route-2",
        target: "node-mar-general",
        label: "general_qa",
        style: { stroke: "#10b981" },
      },
      { id: "e-docs-out", source: "node-mar-retriever", target: "node-mar-response" },
      { id: "e-api-out", source: "node-mar-http", target: "node-mar-response" },
      { id: "e-gen-out", source: "node-mar-general", target: "node-mar-response" },
    ],
  },
];
